#!/bin/sh

print_usage() {
    cat <<-EOF
Options:
    build  :: builds the flake in ./results
    switch :: install the flake in ~/.config
    darwin :: switch using nix-darwin
EOF
exit "$1"
}

case "$1" in
    devenv)
        nix profile install nixpkgs#cachix
        cachix use devenv
        nix profile install --accept-flake-config github:cachix/devenv/latest
        ;;
    upgrade)
        nix flake lock \
            --update-input nixpkgs \
            --update-input home-manager \
            --update-input darwin \
            --update-input homeage \
            --update-input emacs-overlay
        ;;

    build)
        nix run . build -- --flake . --show-trace
        ;;

    switch)
        nix run . switch -- --flake .
        ;;
    darwin)
        nix build "./#darwinConfigurations.$2.system"
        ./result/sw/bin/darwin-rebuild switch --flake ./
        ;;
    *)
        print_usage 0
        ;;
esac
