#!/bin/sh

print_usage() {
    cat <<-EOF
Options:
    build  :: builds the flake in ./results
    switch :: install the flake in ~/.config
    darwin :: switch using nix-darwin
EOF
exit "$1"
}

case "$1" in
    build)
        nix run . build -- --flake . --show-trace
        ;;

    switch)
        nix run . switch -- --flake .
        ;;
    darwin)
        nix build "./#darwinConfigurations.$2.system"
        ./result/sw/bin/darwin-rebuild switch --flake ./
        ;;
    *)
        print_usage 0
        ;;
esac
